# Generated by Django 2.2.3 on 2020-02-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_user', '0002_botuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='herb_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID в Pyramid'),
        ),
    ]
