# Generated by Django 2.2.3 on 2020-03-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_user', '0003_auto_20200227_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_weight', models.IntegerField(default=1, verbose_name='Сортировка (чем меньше, тем выше)')),
                ('question', models.CharField(max_length=64, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order_weight', 'question'],
            },
        ),
    ]
