# Generated by Django 2.2.3 on 2021-05-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_user', '0005_assignee_menunode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menunode',
            name='issue_type',
            field=models.CharField(blank=True, choices=[('10005', 'История'), ('10008', 'Ошибка')], max_length=6, null=True, verbose_name='Какой тип задачи заводить'),
        ),
    ]
