# Generated by Django 2.2.3 on 2019-12-22 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_user_id', models.CharField(max_length=64, verbose_name='ID пользователя в ТГ')),
                ('theme', models.CharField(max_length=16, verbose_name='Тема обращения')),
                ('is_done', models.BooleanField(default=False, verbose_name='Обработана ли заявка?')),
                ('mim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный МИМ')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('is_auto', models.BooleanField(default=True, verbose_name='Автоматический ответ')),
                ('from_user', models.BooleanField(default=True, verbose_name='Сообщение от пользователя?')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст обращения')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Прикреплённый файл')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.SupportRequest', verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
