# Generated by Django 2.2.3 on 2020-02-19 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='message',
            name='sent_to_blinger',
            field=models.BooleanField(default=False, verbose_name='Отправлено ли сообщение в Блингер?'),
        ),
        migrations.AlterField(
            model_name='message',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.SupportRequest', verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='mim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный МИМ'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='theme',
            field=models.CharField(max_length=16, verbose_name='Контекст обращения'),
        ),
    ]
