# Generated by Django 2.2.3 on 2020-02-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20200219_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message/', verbose_name='Прикреплённый файл'),
        ),
    ]
