# Generated by Django 2.2.3 on 2020-07-08 13:50

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20200519_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(verbose_name='ID сообщения')),
                ('user_id', models.IntegerField(verbose_name='ID клиента, запросившего фото')),
                ('request', models.TextField(verbose_name='Запрос клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
            ],
            options={
                'verbose_name': 'Запрос к складу',
                'verbose_name_plural': 'Запросы к складу',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст обращения')),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Прикреплённый файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='support.WarehouseRequest', verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Ответ склада',
                'verbose_name_plural': 'Ответы склада',
                'ordering': ['created_at'],
            },
        ),
    ]
