# Generated by Django 2.2.3 on 2020-09-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_warehouserequest_warehouseresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('issue_id', models.CharField(max_length=16, verbose_name='ID задачи')),
            ],
            options={
                'verbose_name': 'Инцидент',
                'verbose_name_plural': 'Инциденты',
            },
        ),
    ]
